# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'register_frame.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QWidget)

class Ui_Register(object):
    def setupUi(self, Register):
        if not Register.objectName():
            Register.setObjectName(u"Register")
        Register.resize(1320, 900)
        Register.setMinimumSize(QSize(1320, 900))
        Register.setMaximumSize(QSize(1320, 900))
        Register.setSizeIncrement(QSize(1320, 900))
        Register.setStyleSheet(u"background:rgb(255, 238, 172)\n"
"")
        self.centralwidget = QWidget(Register)
        self.centralwidget.setObjectName(u"centralwidget")
        self.register_frame = QFrame(self.centralwidget)
        self.register_frame.setObjectName(u"register_frame")
        self.register_frame.setGeometry(QRect(360, 40, 600, 800))
        self.register_frame.setStyleSheet(u"background:rgb(85, 170, 255)")
        self.register_frame.setFrameShape(QFrame.Shape.Box)
        self.register_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.register_frame.setMidLineWidth(3)
        self.name_label = QLabel(self.register_frame)
        self.name_label.setObjectName(u"name_label")
        self.name_label.setGeometry(QRect(60, 160, 141, 41))
        font = QFont()
        font.setFamilies([u"TH Niramit AS"])
        font.setPointSize(20)
        font.setBold(True)
        self.name_label.setFont(font)
        self.name_label.setFrameShape(QFrame.Shape.Box)
        self.name_label.setLineWidth(3)
        self.name_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.name_lineEdit = QLineEdit(self.register_frame)
        self.name_lineEdit.setObjectName(u"name_lineEdit")
        self.name_lineEdit.setGeometry(QRect(240, 160, 301, 41))
        font1 = QFont()
        font1.setFamilies([u"TH Niramit AS"])
        font1.setPointSize(18)
        font1.setBold(True)
        self.name_lineEdit.setFont(font1)
        self.name_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.lastname_label = QLabel(self.register_frame)
        self.lastname_label.setObjectName(u"lastname_label")
        self.lastname_label.setGeometry(QRect(60, 240, 141, 41))
        self.lastname_label.setFont(font)
        self.lastname_label.setFrameShape(QFrame.Shape.Box)
        self.lastname_label.setLineWidth(3)
        self.lastname_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lastname_lineEdit = QLineEdit(self.register_frame)
        self.lastname_lineEdit.setObjectName(u"lastname_lineEdit")
        self.lastname_lineEdit.setGeometry(QRect(240, 240, 301, 41))
        self.lastname_lineEdit.setFont(font1)
        self.lastname_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.email_label = QLabel(self.register_frame)
        self.email_label.setObjectName(u"email_label")
        self.email_label.setGeometry(QRect(60, 320, 141, 41))
        self.email_label.setFont(font)
        self.email_label.setFrameShape(QFrame.Shape.Box)
        self.email_label.setLineWidth(3)
        self.email_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.email_lineEdit = QLineEdit(self.register_frame)
        self.email_lineEdit.setObjectName(u"email_lineEdit")
        self.email_lineEdit.setGeometry(QRect(240, 320, 301, 41))
        self.email_lineEdit.setFont(font1)
        self.email_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.username_lineEdit = QLineEdit(self.register_frame)
        self.username_lineEdit.setObjectName(u"username_lineEdit")
        self.username_lineEdit.setGeometry(QRect(240, 400, 301, 41))
        self.username_lineEdit.setFont(font1)
        self.username_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.username_label = QLabel(self.register_frame)
        self.username_label.setObjectName(u"username_label")
        self.username_label.setGeometry(QRect(60, 400, 141, 41))
        self.username_label.setFont(font)
        self.username_label.setFrameShape(QFrame.Shape.Box)
        self.username_label.setLineWidth(3)
        self.username_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.password_lineEdit = QLineEdit(self.register_frame)
        self.password_lineEdit.setObjectName(u"password_lineEdit")
        self.password_lineEdit.setGeometry(QRect(240, 480, 301, 41))
        self.password_lineEdit.setFont(font1)
        self.password_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.password_label = QLabel(self.register_frame)
        self.password_label.setObjectName(u"password_label")
        self.password_label.setGeometry(QRect(60, 480, 141, 41))
        self.password_label.setFont(font)
        self.password_label.setFrameShape(QFrame.Shape.Box)
        self.password_label.setLineWidth(3)
        self.password_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.repassword_lineEdit = QLineEdit(self.register_frame)
        self.repassword_lineEdit.setObjectName(u"repassword_lineEdit")
        self.repassword_lineEdit.setGeometry(QRect(240, 560, 301, 41))
        self.repassword_lineEdit.setFont(font1)
        self.repassword_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.repassword_label = QLabel(self.register_frame)
        self.repassword_label.setObjectName(u"repassword_label")
        self.repassword_label.setGeometry(QRect(60, 560, 141, 41))
        self.repassword_label.setFont(font)
        self.repassword_label.setFrameShape(QFrame.Shape.Box)
        self.repassword_label.setLineWidth(3)
        self.repassword_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.head_label = QLabel(self.register_frame)
        self.head_label.setObjectName(u"head_label")
        self.head_label.setGeometry(QRect(60, 20, 481, 101))
        font2 = QFont()
        font2.setFamilies([u"Viner Hand ITC"])
        font2.setPointSize(48)
        font2.setBold(False)
        self.head_label.setFont(font2)
        self.head_label.setFrameShape(QFrame.Shape.Box)
        self.head_label.setLineWidth(3)
        self.head_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.save_pushButton = QPushButton(self.register_frame)
        self.save_pushButton.setObjectName(u"save_pushButton")
        self.save_pushButton.setGeometry(QRect(60, 670, 221, 81))
        font3 = QFont()
        font3.setFamilies([u"TH Niramit AS"])
        font3.setPointSize(26)
        font3.setBold(True)
        self.save_pushButton.setFont(font3)
        self.save_pushButton.setStyleSheet(u"background:rgb(85, 255, 127)")
        self.cancle_pushButton = QPushButton(self.register_frame)
        self.cancle_pushButton.setObjectName(u"cancle_pushButton")
        self.cancle_pushButton.setGeometry(QRect(320, 670, 221, 81))
        self.cancle_pushButton.setFont(font3)
        self.cancle_pushButton.setStyleSheet(u"background:rgb(255, 85, 0)")
        Register.setCentralWidget(self.centralwidget)

        self.retranslateUi(Register)

        QMetaObject.connectSlotsByName(Register)
    # setupUi

    def retranslateUi(self, Register):
        Register.setWindowTitle(QCoreApplication.translate("Register", u"REGISTER", None))
        self.name_label.setText(QCoreApplication.translate("Register", u"\u0e0a\u0e37\u0e48\u0e2d", None))
        self.lastname_label.setText(QCoreApplication.translate("Register", u"\u0e19\u0e32\u0e21\u0e2a\u0e01\u0e38\u0e25", None))
        self.email_label.setText(QCoreApplication.translate("Register", u"EMAIL", None))
        self.username_label.setText(QCoreApplication.translate("Register", u"USERNAME", None))
        self.password_label.setText(QCoreApplication.translate("Register", u"PASSWORD", None))
        self.repassword_label.setText(QCoreApplication.translate("Register", u"PASSWORD", None))
        self.head_label.setText(QCoreApplication.translate("Register", u"R E G I S T E R", None))
        self.save_pushButton.setText(QCoreApplication.translate("Register", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.cancle_pushButton.setText(QCoreApplication.translate("Register", u"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01", None))
    # retranslateUi

